In [1]:

# imports
import os
import sys
import types
import json
import base64

# figure size/format
fig_width = 5.5
fig_height = 3.5
fig_format = 'pdf'
fig_dpi = 300
interactivity = ''
is_shiny = False
is_dashboard = False
plotly_connected = True

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = "figure"

  # IPython 7.14 deprecated set_matplotlib_formats from IPython
  try:
    from matplotlib_inline.backend_inline import set_matplotlib_formats
  except ImportError:
    # Fall back to deprecated location for older IPython versions
    from IPython.display import set_matplotlib_formats
    
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  if plotly_connected:
    pio.renderers.default = "notebook_connected"
  else:
    pio.renderers.default = "notebook"
  for template in pio.templates.keys():
    pio.templates[template].layout.margin = dict(t=30,r=0,b=0,l=0)
except Exception:
  pass

# disable itables paging for dashboards
if is_dashboard:
  try:
    from itables import options
    options.dom = 'fiBrtlp'
    options.maxBytes = 1024 * 1024
    options.language = dict(info = "Showing _TOTAL_ entries")
    options.classes = "display nowrap compact"
    options.paging = False
    options.searching = True
    options.ordering = True
    options.info = True
    options.lengthChange = False
    options.autoWidth = False
    options.responsive = True
    options.keys = True
    options.buttons = []
  except Exception:
    pass
  
  try:
    import altair as alt
    # By default, dashboards will have container sized
    # vega visualizations which allows them to flow reasonably
    theme_sentinel = '_quarto-dashboard-internal'
    def make_theme(name):
        nonTheme = alt.themes._plugins[name]    
        def patch_theme(*args, **kwargs):
            existingTheme = nonTheme()
            if 'height' not in existingTheme:
              existingTheme['height'] = 'container'
            if 'width' not in existingTheme:
              existingTheme['width'] = 'container'

            if 'config' not in existingTheme:
              existingTheme['config'] = dict()
            
            # Configure the default font sizes
            title_font_size = 15
            header_font_size = 13
            axis_font_size = 12
            legend_font_size = 12
            mark_font_size = 12
            tooltip = False

            config = existingTheme['config']

            # The Axis
            if 'axis' not in config:
              config['axis'] = dict()
            axis = config['axis']
            if 'labelFontSize' not in axis:
              axis['labelFontSize'] = axis_font_size
            if 'titleFontSize' not in axis:
              axis['titleFontSize'] = axis_font_size  

            # The legend
            if 'legend' not in config:
              config['legend'] = dict()
            legend = config['legend']
            if 'labelFontSize' not in legend:
              legend['labelFontSize'] = legend_font_size
            if 'titleFontSize' not in legend:
              legend['titleFontSize'] = legend_font_size  

            # The header
            if 'header' not in config:
              config['header'] = dict()
            header = config['header']
            if 'labelFontSize' not in header:
              header['labelFontSize'] = header_font_size
            if 'titleFontSize' not in header:
              header['titleFontSize'] = header_font_size    

            # Title
            if 'title' not in config:
              config['title'] = dict()
            title = config['title']
            if 'fontSize' not in title:
              title['fontSize'] = title_font_size

            # Marks
            if 'mark' not in config:
              config['mark'] = dict()
            mark = config['mark']
            if 'fontSize' not in mark:
              mark['fontSize'] = mark_font_size

            # Mark tooltips
            if tooltip and 'tooltip' not in mark:
              mark['tooltip'] = dict(content="encoding")

            return existingTheme
            
        return patch_theme

    # We can only do this once per session
    if theme_sentinel not in alt.themes.names():
      for name in alt.themes.names():
        alt.themes.register(name, make_theme(name))
      
      # register a sentinel theme so we only do this once
      alt.themes.register(theme_sentinel, make_theme('default'))
      alt.themes.enable('default')

  except Exception:
    pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass

# interactivity
if interactivity:
  from IPython.core.interactiveshell import InteractiveShell
  InteractiveShell.ast_node_interactivity = interactivity

# NOTE: the kernel_deps code is repeated in the cleanup.py file
# (we can't easily share this code b/c of the way it is run).
# If you edit this code also edit the same code in cleanup.py!

# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  if not os.path.exists(path):
    continue
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))

# set run_path if requested
run_path = 'QzpcVXNlcnNcbG9pY2hcRG9jdW1lbnRzXFdvcmtcR2l0aHViXHF1YXJ0b1xweXRob25faWFfcXVhcnRvXG1vZHVsZXNcbW9kdWxlXzAy'
if run_path:
  # hex-decode the path
  run_path = base64.b64decode(run_path.encode("utf-8")).decode("utf-8")
  os.chdir(run_path)

# reset state
%reset

# shiny
# Checking for shiny by using False directly because we're after the %reset. We don't want
# to set a variable that stays in global scope.
if False:
  try:
    import htmltools as _htmltools
    import ast as _ast

    _htmltools.html_dependency_render_mode = "json"

    # This decorator will be added to all function definitions
    def _display_if_has_repr_html(x):
      try:
        # IPython 7.14 preferred import
        from IPython.display import display, HTML
      except:
        from IPython.core.display import display, HTML

      if hasattr(x, '_repr_html_'):
        display(HTML(x._repr_html_()))
      return x

    # ideally we would undo the call to ast_transformers.append
    # at the end of this block whenver an error occurs, we do 
    # this for now as it will only be a problem if the user 
    # switches from shiny to not-shiny mode (and even then likely
    # won't matter)
    import builtins
    builtins._display_if_has_repr_html = _display_if_has_repr_html

    class _FunctionDefReprHtml(_ast.NodeTransformer):
      def visit_FunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

      def visit_AsyncFunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

    ip = get_ipython()
    ip.ast_transformers.append(_FunctionDefReprHtml())

  except:
    pass

def ojs_define(**kwargs):
  import json
  try:
    # IPython 7.14 preferred import
    from IPython.display import display, HTML
  except:
    from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.Series:
      v = pd.DataFrame(v)
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v

  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define
globals()["__spec__"] = None

{"C:\\Users\\loich\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\_bootstrap.py": 1727748220.0, "C:\\Users\\loich\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\importlib\\_bootstrap_external.py": 1727748220.0, "C:\\Users\\loich\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\zipimport.py": 1727748220.0, "C:\\Users\\loich\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\codecs.py": 1727748220.0, "C:\\Users\\loich\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\encodings\\aliases.py": 1727748220.0, "C:\\Users\\loich\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\encodings\\__init__.py": 1727748220.0, "C:\\Users\\loich\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\encodings\\utf_8.py": 1727748220.0, "C:\\Users\\loich\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\encodings\\cp1252.py": 1727748220.0, "C:\\Users\\loich\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\abc.py": 1727748220.0, "C:\\Users\\loich\\AppData\\Local\\Programs\\Python\\Python

In [2]:
#| label: setup
import numpy as np
import matplotlib.pyplot as plt

plt.rcParams['figure.figsize'] = (9, 5)
np.random.seed(42)

print(f"✅ NumPy {np.__version__}")

✅ NumPy 2.2.6


In [3]:
# 1. Depuis une liste (tu connais)
a = np.array([1, 2, 3, 4, 5])
print(f"array     : {a}")

# 2. Zéros et uns (pour initialiser)
z = np.zeros(5)
u = np.ones((2, 3))  # matrice 2x3 de 1
print(f"zeros     : {z}")
print(f"ones (2x3) :\n{u}")

# 3. arange : comme range() mais en NumPy
r = np.arange(0, 10, 2)  # de 0 à 10 (exclu), pas de 2
print(f"arange    : {r}")

# 4. linspace : nombre fixe de points équidistants
l = np.linspace(0, 1, 5)  # 5 valeurs entre 0 et 1
print(f"linspace  : {l}")

# 5. full : remplir avec une valeur spécifique
f = np.full((2, 3), 7.0)
print(f"full (7)  :\n{f}")

# 6. eye : matrice identité
i = np.eye(3)
print(f"eye (3x3) :\n{i}")

# 7. Aléatoire uniforme entre 0 et 1
rand = np.random.random(4)
print(f"random    : {rand}")

# 8. Aléatoire normal (gaussien)
gauss = np.random.randn(4)
print(f"randn     : {gauss}")

array     : [1 2 3 4 5]
zeros     : [0. 0. 0. 0. 0.]
ones (2x3) :
[[1. 1. 1.]
 [1. 1. 1.]]
arange    : [0 2 4 6 8]
linspace  : [0.   0.25 0.5  0.75 1.  ]
full (7)  :
[[7. 7. 7.]
 [7. 7. 7.]]
eye (3x3) :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
random    : [0.37454012 0.95071431 0.73199394 0.59865848]
randn     : [-0.23415337 -0.23413696  1.57921282  0.76743473]


In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(f"shape : {a.shape}")   # (2, 3) — 2 lignes, 3 colonnes
print(f"ndim  : {a.ndim}")    # 2 — nombre de dimensions
print(f"size  : {a.size}")    # 6 — nombre total d'éléments
print(f"dtype : {a.dtype}")   # int64 — type des éléments
print(f"nbytes: {a.nbytes}")  # 48 — taille en mémoire

shape : (2, 3)
ndim  : 2
size  : 6
dtype : int64
nbytes: 48


In [5]:
#| eval: false
# TODO: Exercice 1

# 1. 20 premiers nombres impairs


# 2. Matrice 4x4 de -1


# 3. 100 points entre -π et π


# 4. Identité 3x3 + attributs


# 5. Array aléatoire 5x5 d'entiers 0-100

In [6]:
# 1. arange(1, 40, 2) donne 1, 3, 5, ..., 39 — 20 valeurs
impairs = np.arange(1, 40, 2)
print(f"Impairs : {impairs}")

# 2. full
mat = np.full((4, 4), -1)
print(f"\nMatrice -1 :\n{mat}")

# 3. linspace avec numpy.pi
points = np.linspace(-np.pi, np.pi, 100)
print(f"\nPoints : premier = {points[0]:.3f}, dernier = {points[-1]:.3f}")

# 4. Identité + attributs
I = np.eye(3)
print(f"\nIdentité :\n{I}")
print(f"shape = {I.shape}, ndim = {I.ndim}, size = {I.size}, dtype = {I.dtype}")

# 5. Random int
rand_mat = np.random.randint(0, 100, size=(5, 5))
print(f"\nAléatoire :\n{rand_mat}")

Impairs : [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]

Matrice -1 :
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]

Points : premier = -3.142, dernier = 3.142

Identité :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
shape = (3, 3), ndim = 2, size = 9, dtype = float64

Aléatoire :
[[21 52  1 87 29]
 [37  1 63 59 20]
 [32 75 57 21 88]
 [48 90 58 41 91]
 [59 79 14 61 61]]


In [7]:
# Pour un array 1D
a = np.array([10, 20, 30, 40, 50])
print(f"a[0]  : {a[0]}")      # 10 (premier)
print(f"a[-1] : {a[-1]}")     # 50 (dernier)

# Pour un array 2D : [ligne, colonne]
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(f"\nm[1, 2] : {m[1, 2]}")  # 6 (ligne 1, colonne 2)
print(f"m[0]    : {m[0]}")       # [1 2 3] (toute la ligne 0)

a[0]  : 10
a[-1] : 50

m[1, 2] : 6
m[0]    : [1 2 3]


In [8]:
a = np.arange(10)
print(f"a              : {a}")
print(f"a[2:5]         : {a[2:5]}")       # indices 2 à 4
print(f"a[::2]         : {a[::2]}")       # un sur deux
print(f"a[::-1]        : {a[::-1]}")      # inversé
print(f"a[-3:]         : {a[-3:]}")       # les 3 derniers

a              : [0 1 2 3 4 5 6 7 8 9]
a[2:5]         : [2 3 4]
a[::2]         : [0 2 4 6 8]
a[::-1]        : [9 8 7 6 5 4 3 2 1 0]
a[-3:]         : [7 8 9]


In [9]:
m = np.arange(16).reshape(4, 4)
print(f"Matrice :\n{m}\n")

print(f"m[1:3, 1:3] (sous-matrice 2x2 au centre) :\n{m[1:3, 1:3]}")
print(f"\nm[:, 0] (première colonne)        : {m[:, 0]}")
print(f"m[0, :] (première ligne)          : {m[0, :]}")
print(f"m[::2, ::2] (un sur deux)         :\n{m[::2, ::2]}")

Matrice :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

m[1:3, 1:3] (sous-matrice 2x2 au centre) :
[[ 5  6]
 [ 9 10]]

m[:, 0] (première colonne)        : [ 0  4  8 12]
m[0, :] (première ligne)          : [0 1 2 3]
m[::2, ::2] (un sur deux)         :
[[ 0  2]
 [ 8 10]]


In [10]:
ages = np.array([25, 17, 42, 8, 31, 65, 12, 55, 22, 88])

# Créer un masque
majeurs = ages >= 18
print(f"Masque : {majeurs}")

# Appliquer le masque
print(f"Âges majeurs : {ages[majeurs]}")

# En une seule ligne (le plus fréquent)
print(f"Âges ≥ 18    : {ages[ages >= 18]}")

Masque : [ True False  True False  True  True False  True  True  True]
Âges majeurs : [25 42 31 65 55 22 88]
Âges ≥ 18    : [25 42 31 65 55 22 88]


In [11]:
# Âges entre 20 et 60
print(f"Entre 20 et 60 : {ages[(ages >= 20) & (ages <= 60)]}")

# Âges < 18 OU > 65
print(f"Mineurs ou 65+ : {ages[(ages < 18) | (ages > 65)]}")

Entre 20 et 60 : [25 42 31 55 22]
Mineurs ou 65+ : [17  8 12 88]


In [12]:
# Simuler un petit dataset : [âge, salaire]
data = np.array([
    [25, 35000],
    [42, 65000],
    [33, 45000],
    [55, 85000],
    [28, 42000],
    [61, 95000],
    [38, 55000]
])

# Question : quelles sont les personnes gagnant plus de 50 000 € ?
hauts_salaires = data[data[:, 1] > 50000]
print("Personnes à haut salaire :")
print(hauts_salaires)

# Question : âges des personnes gagnant plus de 50 000 € ?
ages_hauts = data[data[:, 1] > 50000, 0]
print(f"\nLeurs âges : {ages_hauts}")

Personnes à haut salaire :
[[   42 65000]
 [   55 85000]
 [   61 95000]
 [   38 55000]]

Leurs âges : [42 55 61 38]


In [13]:
a = np.array([10, 20, 30, 40, 50, 60, 70])

# Sélectionner plusieurs éléments non contigus
indices = [0, 2, 5]
print(f"Éléments 0, 2, 5 : {a[indices]}")

# Réordonner
ordre = [6, 5, 4, 3, 2, 1, 0]
print(f"Inversé (fancy)  : {a[ordre]}")

# Pour les matrices : on donne les indices ligne ET colonne
m = np.arange(12).reshape(3, 4)
print(f"\nMatrice :\n{m}")
print(f"\nm[[0,2], [1,3]] : {m[[0, 2], [1, 3]]}")  # (0,1) et (2,3) → 1 et 11

Éléments 0, 2, 5 : [10 30 60]
Inversé (fancy)  : [70 60 50 40 30 20 10]

Matrice :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

m[[0,2], [1,3]] : [ 1 11]


In [14]:
#| eval: false
# TODO: Exercice 2

np.random.seed(0)
data = np.random.randn(1000) * 10 + 50

# 1. Compter les valeurs > 60


# 2. Extraire entre 40 et 60


# 3. Remplacer négatifs par 0


# 4. Max et son indice


# 5. Top 10 valeurs

In [15]:
np.random.seed(0)
data = np.random.randn(1000) * 10 + 50

# 1. Compter
n_sup_60 = np.sum(data > 60)  # True=1, False=0 → sum = nombre de True
print(f"Valeurs > 60 : {n_sup_60}")

# 2. Extraire
entre_40_60 = data[(data >= 40) & (data <= 60)]
print(f"Valeurs entre 40 et 60 : {len(entre_40_60)}")

# 3. Remplacer négatifs (il n'y en a probablement pas ici, mais le principe est là)
data[data < 0] = 0
print(f"Après remplacement, min = {data.min():.2f}")

# 4. Max et indice
max_val = data.max()
idx_max = np.argmax(data)
print(f"Max = {max_val:.2f} à l'indice {idx_max}")

# 5. Top 10 valeurs
# Deux méthodes
top10_sort = np.sort(data)[-10:]      # trier + prendre les 10 derniers
print(f"Top 10 (sort)      : {top10_sort}")

# Alternative plus efficace pour de gros arrays
top10_partition = np.partition(data, -10)[-10:]
top10_partition.sort()
print(f"Top 10 (partition) : {top10_partition}")

Valeurs > 60 : 141
Valeurs entre 40 et 60 : 699
Après remplacement, min = 19.54
Max = 77.59 à l'indice 943
Top 10 (sort)      : [73.03916698 73.39624806 73.46647031 73.80745351 73.83144775 74.1245368
 74.97200392 75.94424588 76.96224053 77.59355114]
Top 10 (partition) : [73.03916698 73.39624806 73.46647031 73.80745351 73.83144775 74.1245368
 74.97200392 75.94424588 76.96224053 77.59355114]


In [16]:
v = np.array([1, 2, 3, 4, 5])
print(v * 10)  # [10 20 30 40 50]

[10 20 30 40 50]


In [17]:
# Notre dataset : 3 individus, 4 caractéristiques
donnees = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

# On veut soustraire à chaque individu la moyenne de chaque colonne
moyennes = donnees.mean(axis=0)  # moyenne par colonne → shape (4,)
print(f"Moyennes : {moyennes}")

# Broadcasting : NumPy étire automatiquement le vecteur pour qu'il matche
donnees_centrees = donnees - moyennes
print(f"\nDonnées centrées :\n{donnees_centrees}")

Moyennes : [50. 60. 70. 80.]

Données centrées :
[[-40. -40. -40. -40.]
 [  0.   0.   0.   0.]
 [ 40.  40.  40.  40.]]


In [18]:
# Générer des données bruitées
X = np.random.randn(5, 3) * 10 + 100
print(f"X :\n{X}\n")

# En une seule ligne : centrage + mise à l'écart-type (normalisation)
X_norm = (X - X.mean(axis=0)) / X.std(axis=0)
print(f"X normalisé :\n{X_norm}")
print(f"\nMoyenne par colonne : {X_norm.mean(axis=0).round(3)}")
print(f"Std par colonne     : {X_norm.std(axis=0).round(3)}")

X :
[[105.5596268  108.92473887  95.77685176]
 [101.04714029 102.28053325 102.01479947]
 [105.40773585  81.8192237   99.5067593 ]
 [102.39033601  89.99669651 116.73985707]
 [101.61559267 115.63404745  92.09476978]]

X normalisé :
[[ 1.23319763  0.74594227 -0.64465461]
 [-1.12922735  0.20685586  0.09323567]
 [ 1.15367806 -1.45329955 -0.20344179]
 [-0.42602323 -0.78980948  1.83507086]
 [-0.83162511  1.29031089 -1.08021012]]

Moyenne par colonne : [ 0.  0. -0.]
Std par colonne     : [1. 1. 1.]


In [19]:
# 4 points dans le plan
points = np.array([
    [0, 0],
    [3, 0],
    [0, 4],
    [3, 4]
])

# Matrice de distances : points[:, None] a shape (4, 1, 2)
# points[None, :] a shape (1, 4, 2)
# La différence a shape (4, 4, 2) : toutes les paires de différences
differences = points[:, None, :] - points[None, :, :]
distances = np.linalg.norm(differences, axis=-1)

print(f"Matrice de distances :\n{distances.round(2)}")

Matrice de distances :
[[0. 3. 4. 5.]
 [3. 0. 5. 4.]
 [4. 5. 0. 3.]
 [5. 4. 3. 0.]]


In [20]:
#| eval: false
# TODO: Exercice 3

# 1. Centrage des notes


# 2. Table de multiplication (sans boucle)


# 3. Distances à l'origine

In [21]:
# 1. Centrage des notes
notes = np.array([
    [10, 12, 8],
    [14, 16, 15],
    [6, 7, 9],
    [13, 11, 12]
])

moyennes_DS = notes.mean(axis=0)  # shape (3,)
notes_centrees = notes - moyennes_DS  # broadcasting (4,3) - (3,) → (4,3)
print("Notes centrées :")
print(notes_centrees)
print(f"Vérif : moyennes après centrage = {notes_centrees.mean(axis=0)}")

Notes centrées :
[[-0.75  0.5  -3.  ]
 [ 3.25  4.5   4.  ]
 [-4.75 -4.5  -2.  ]
 [ 2.25 -0.5   1.  ]]
Vérif : moyennes après centrage = [0. 0. 0.]


In [22]:
# 2. Table de multiplication
# arange crée [1..10], [:, None] transforme en colonne (10,1)
# np.arange(1,11) reste en ligne (10,) → broadcasting (10,1) * (10,) = (10,10)
table = np.arange(1, 11)[:, None] * np.arange(1, 11)
print("Table de multiplication :")
print(table)

Table de multiplication :
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [23]:
# 3. Distances à l'origine
np.random.seed(42)
points = np.random.randn(100, 2)

distances = np.linalg.norm(points, axis=1)
print(f"100 distances calculées")
print(f"Min : {distances.min():.3f}, Max : {distances.max():.3f}, Moy : {distances.mean():.3f}")

100 distances calculées
Min : 0.235, Max : 2.746, Moy : 1.185


In [24]:
a = np.array([1, 4, 9, 16, 25])

print(f"sqrt : {np.sqrt(a)}")
print(f"exp  : {np.exp(a)[:3]}...")
print(f"log  : {np.log(a).round(2)}")
print(f"sin  : {np.sin(a).round(3)}")

sqrt : [1. 2. 3. 4. 5.]
exp  : [2.71828183e+00 5.45981500e+01 8.10308393e+03]...
log  : [0.   1.39 2.2  2.77 3.22]
sin  : [ 0.841 -0.757  0.412 -0.288 -0.132]


In [25]:
import time

# Un gros array
N = 1_000_000
a = np.random.randn(N)

# Méthode 1 : boucle Python
start = time.time()
result_boucle = [x**2 for x in a]
temps_boucle = time.time() - start

# Méthode 2 : ufunc NumPy
start = time.time()
result_numpy = a ** 2
temps_numpy = time.time() - start

print(f"Boucle Python : {temps_boucle*1000:.1f} ms")
print(f"NumPy ufunc   : {temps_numpy*1000:.1f} ms")
print(f"Ratio         : {temps_boucle / temps_numpy:.0f}x plus rapide")

Boucle Python : 108.2 ms
NumPy ufunc   : 2.0 ms
Ratio         : 54x plus rapide


In [26]:
a = np.array([-3, -1, 0, 2, 4])

# Arithmétique
print(f"abs    : {np.abs(a)}")
print(f"square : {np.square(a)}")
print(f"sqrt   : {np.sqrt(np.abs(a))}")  # racines des valeurs absolues

# Arrondis
b = np.array([1.2, 2.7, -3.4, 5.5])
print(f"round  : {np.round(b)}")
print(f"floor  : {np.floor(b)}")
print(f"ceil   : {np.ceil(b)}")

# Comparaisons (retournent des booléens)
c = np.array([1, 5, 3, 7, 2])
print(f"max de c : {np.maximum(c, 4)}")   # élément par élément : max(c[i], 4)

abs    : [3 1 0 2 4]
square : [ 9  1  0  4 16]
sqrt   : [1.73205081 1.         0.         1.41421356 2.        ]
round  : [ 1.  3. -3.  6.]
floor  : [ 1.  2. -4.  5.]
ceil   : [ 2.  3. -3.  6.]
max de c : [4 5 4 7 4]


In [27]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f"sum total    : {a.sum()}")         # 45
print(f"sum par col. : {a.sum(axis=0)}")   # [12 15 18]
print(f"sum par lig. : {a.sum(axis=1)}")   # [6 15 24]

print(f"\nmean : {a.mean()}")
print(f"max  : {a.max()}")
print(f"min  : {a.min()}")
print(f"std  : {a.std():.3f}")
print(f"argmax (indice du max) : {a.argmax()}")

sum total    : 45
sum par col. : [12 15 18]
sum par lig. : [ 6 15 24]

mean : 5.0
max  : 9
min  : 1
std  : 2.582
argmax (indice du max) : 8


In [28]:
m = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Matrice shape : {m.shape}  (2 lignes, 3 colonnes)\n")

print(f"sum(axis=0) → shape {m.sum(axis=0).shape}")
print(f"  Valeur : {m.sum(axis=0)}  (une valeur par colonne)")

print(f"\nsum(axis=1) → shape {m.sum(axis=1).shape}")
print(f"  Valeur : {m.sum(axis=1)}  (une valeur par ligne)")

Matrice shape : (2, 3)  (2 lignes, 3 colonnes)

sum(axis=0) → shape (3,)
  Valeur : [5 7 9]  (une valeur par colonne)

sum(axis=1) → shape (2,)
  Valeur : [ 6 15]  (une valeur par ligne)


In [29]:
#| eval: false
# TODO: Exercice 4

np.random.seed(42)
notes = np.random.uniform(5, 20, size=(30, 5))
matieres = ['Maths', 'Français', 'Histoire', 'Anglais', 'Sport']

# 1. Moyenne par étudiant


# 2. Moyenne par matière


# 3. Matière avec meilleure moyenne


# 4. Étudiants avec moyenne ≥ 12


# 5. Meilleur étudiant


# 6. Matière la plus dispersée

In [30]:
np.random.seed(42)
notes = np.random.uniform(5, 20, size=(30, 5))
matieres = ['Maths', 'Français', 'Histoire', 'Anglais', 'Sport']

# 1. Moyenne par étudiant (on écrase les colonnes → axis=1)
moy_etudiants = notes.mean(axis=1)
print(f"Moyennes des 5 premiers étudiants : {moy_etudiants[:5].round(2)}")

# 2. Moyenne par matière (on écrase les lignes → axis=0)
moy_matieres = notes.mean(axis=0)
for nom, moy in zip(matieres, moy_matieres):
    print(f"  {nom:10s} : {moy:.2f}")

# 3. Matière avec meilleure moyenne
idx_best = np.argmax(moy_matieres)
print(f"\nMeilleure matière : {matieres[idx_best]} ({moy_matieres[idx_best]:.2f})")

# 4. Étudiants ≥ 12
n_bons = np.sum(moy_etudiants >= 12)
print(f"Étudiants à ≥12 : {n_bons}")

# 5. Meilleur étudiant
idx_meilleur = np.argmax(moy_etudiants)
print(f"Meilleur étudiant : n°{idx_meilleur} avec {moy_etudiants[idx_meilleur]:.2f}")

# 6. Matière la plus dispersée
stds = notes.std(axis=0)
idx_disperse = np.argmax(stds)
print(f"Matière la plus dispersée : {matieres[idx_disperse]} (std={stds[idx_disperse]:.2f})")

Moyennes des 5 premiers étudiants : [13.44 12.17 11.65 10.21 10.6 ]
  Maths      : 12.44
  Français   : 12.03
  Histoire   : 12.33
  Anglais    : 11.79
  Sport      : 11.87

Meilleure matière : Maths (12.44)
Étudiants à ≥12 : 15
Meilleur étudiant : n°10 avec 17.53
Matière la plus dispersée : Anglais (std=4.52)


In [31]:
a = np.arange(12)
print(f"a (shape {a.shape}) : {a}")

# Transformer en matrice 3x4
m = a.reshape(3, 4)
print(f"\nreshape(3, 4) :\n{m}")

# -1 signifie "calcule automatiquement"
m2 = a.reshape(2, -1)  # 2 lignes, ? colonnes → 6
print(f"\nreshape(2, -1) :\n{m2}")

a (shape (12,)) : [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshape(3, 4) :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

reshape(2, -1) :
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [32]:
m = np.arange(12).reshape(3, 4)

# flatten : copie
flat = m.flatten()
print(f"flatten : {flat}")

# ravel : vue (plus rapide, mais partage la mémoire)
raveled = m.ravel()
print(f"ravel   : {raveled}")

flatten : [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravel   : [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [33]:
m = np.array([[1, 2, 3], [4, 5, 6]])
print(f"m (shape {m.shape}) :\n{m}\n")
print(f"m.T (shape {m.T.shape}) :\n{m.T}")

m (shape (2, 3)) :
[[1 2 3]
 [4 5 6]]

m.T (shape (3, 2)) :
[[1 4]
 [2 5]
 [3 6]]


In [34]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Horizontalement (côte à côte)
h = np.hstack([a, b])
print(f"hstack : {h}")

# Verticalement (empiler)
v = np.vstack([a, b])
print(f"\nvstack :\n{v}")

# Plus général : concatenate avec axis
c = np.concatenate([a, b])
print(f"\nconcatenate : {c}")

hstack : [1 2 3 4 5 6]

vstack :
[[1 2 3]
 [4 5 6]]

concatenate : [1 2 3 4 5 6]


In [35]:
ages = np.array([15, 22, 17, 45, 30, 12, 65])

# Si âge ≥ 18, retourne "Adulte", sinon "Mineur"
categories = np.where(ages >= 18, 'Adulte', 'Mineur')
print(categories)

# Avec des valeurs numériques : remplacer les valeurs hors plage
notes = np.array([8, 15, 22, 10, -3, 25])  # certaines sont invalides
notes_clean = np.where((notes < 0) | (notes > 20), np.nan, notes)
print(f"\nNotes nettoyées : {notes_clean}")

['Mineur' 'Adulte' 'Mineur' 'Adulte' 'Adulte' 'Mineur' 'Adulte']

Notes nettoyées : [ 8. 15. nan 10. nan nan]


In [36]:
#| eval: false
# TODO: Exercice 5

# 1. Array 3D


# 2. Ventes : transposition + classification

In [37]:
# 1. Array 3D
a = np.arange(1, 25).reshape(2, 3, 4)
print(f"Shape : {a.shape}")
print(f"Array :\n{a}")

Shape : (2, 3, 4)
Array :
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [38]:
# 2. Ventes
ventes = np.array([
    [100, 150, 200, 180],
    [80, 95, 105, 110],
    [45, 40, 52, 48],
    [200, 220, 195, 210],
    [15, 12, 18, 14]
])

# a. Transposition
ventes_T = ventes.T
print(f"Shape transposée : {ventes_T.shape} (4 trimestres, 5 produits)")
print(ventes_T)

# b. Classification
# On imbrique deux np.where
categories = np.where(
    ventes < 50, 
    'faible',
    np.where(ventes > 150, 'forte', 'moyenne')
)
print(f"\nCatégories :\n{categories}")

Shape transposée : (4, 5) (4 trimestres, 5 produits)
[[100  80  45 200  15]
 [150  95  40 220  12]
 [200 105  52 195  18]
 [180 110  48 210  14]]

Catégories :
[['moyenne' 'moyenne' 'forte' 'forte']
 ['moyenne' 'moyenne' 'moyenne' 'moyenne']
 ['faible' 'faible' 'moyenne' 'faible']
 ['forte' 'forte' 'forte' 'forte']
 ['faible' 'faible' 'faible' 'faible']]


In [39]:
#| eval: false
# TODO: Exercice bilan

np.random.seed(42)
n = 50
surfaces = np.random.uniform(20, 150, n)
occupants = np.random.randint(1, 6, n)
ages_batiment = np.random.randint(0, 80, n)
prix = (2500 * surfaces + 5000 * occupants - 500 * ages_batiment 
        + np.random.normal(0, 10000, n) + 50000)
prix[3] = 9_999_999
prix[17] = np.nan
surfaces[25] = 500

# 1-8. À toi !

In [40]:
np.random.seed(42)
n = 50
surfaces = np.random.uniform(20, 150, n)
occupants = np.random.randint(1, 6, n)
ages_batiment = np.random.randint(0, 80, n)
prix = (2500 * surfaces + 5000 * occupants - 500 * ages_batiment 
        + np.random.normal(0, 10000, n) + 50000)
prix[3] = 9_999_999
prix[17] = np.nan
surfaces[25] = 500

# 1. Masque NaN
has_nan = np.isnan(prix)
print(f"NaN dans prix : {has_nan.sum()}")

# 2. Imputation par la médiane
mediane_prix = np.nanmedian(prix)  # ignore les NaN
prix = np.where(has_nan, mediane_prix, prix)
print(f"Après imputation : {np.isnan(prix).sum()} NaN restants")

# 3. Détection outliers par IQR
def detecter_outliers_iqr(x):
    q1 = np.percentile(x, 25)
    q3 = np.percentile(x, 75)
    iqr = q3 - q1
    return (x < q1 - 1.5*iqr) | (x > q3 + 1.5*iqr)

out_prix = detecter_outliers_iqr(prix)
out_surf = detecter_outliers_iqr(surfaces)
print(f"Outliers prix     : {out_prix.sum()}")
print(f"Outliers surface  : {out_surf.sum()}")

# 4. Masque global (à GARDER = non outlier)
a_garder = ~(out_prix | out_surf)
print(f"Lignes à garder   : {a_garder.sum()} sur {n}")

# Appliquer le masque à toutes les variables
surfaces_clean = surfaces[a_garder]
occupants_clean = occupants[a_garder]
ages_clean = ages_batiment[a_garder]
prix_clean = prix[a_garder]

# 5. Construire X (on empile les colonnes)
X = np.column_stack([surfaces_clean, occupants_clean, ages_clean])
print(f"\nShape de X : {X.shape}")

# 6. Normalisation en UNE ligne grâce au broadcasting
X_norm = (X - X.mean(axis=0)) / X.std(axis=0)
print(f"Moyennes après normalisation : {X_norm.mean(axis=0).round(3)}")
print(f"Std après normalisation      : {X_norm.std(axis=0).round(3)}")

# 7. Corrélation surface/prix
corr = np.corrcoef(surfaces_clean, prix_clean)[0, 1]
print(f"\nCorrélation surface ↔ prix : {corr:.3f}")

# 8. Résumé final
print(f"\n=== Résumé ===")
print(f"Lignes finales : {X.shape[0]}")
print(f"Shape X_norm   : {X_norm.shape}")

NaN dans prix : 1
Après imputation : 0 NaN restants
Outliers prix     : 1
Outliers surface  : 1
Lignes à garder   : 48 sur 50

Shape de X : (48, 3)
Moyennes après normalisation : [ 0.  0. -0.]
Std après normalisation      : [1. 1. 1.]

Corrélation surface ↔ prix : 0.987

=== Résumé ===
Lignes finales : 48
Shape X_norm   : (48, 3)
